### PR TITLE
Docker ttn dashboard v1.0

### PR DESCRIPTION
**Pull request by MuruganChandrasekar**
Please check it and let me know if changes required.

--Murugan Chandrasekar

### CODE REVIEW

**Comment by MuruganChandrasekar** [comment]
> Why is line 70 needed ?

As you can see in the Dockerfile that we are using `FROM phusion/baseimage`, we have to keep scripts that we want to run during startup.

Please refer link: https://github.com/phusion/baseimage-docker 

In the README.md file, it is saying like below.

Running scripts during container startup
The baseimage-docker init system, /sbin/my_init, runs the following scripts during startup, in the following order:

All executable scripts in /etc/my_init.d, if this directory exists. The scripts are run in lexicographic order.
The script /etc/rc.local, if this file exists.
All scripts must exit correctly, e.g. with exit code 0. If any script exits with a non-zero exit code, the booting will fail.

**Comment by MuruganChandrasekar** [comment]
> I was wondering why the `mkdir -p /etc/my_init.d` because of line 66 (`COPY`), so `/etc/my_init.d` already exists then, or did I miss something ?

Yes you are right!. No need to create `/etc/my_init.d` directory in the `phusion/baseimage` since the directory is existing by default.

Thanks for your inputs on this.

**Comment by terrillmoore** [comment]
@MuruganChandrasekar where are we on this? there are conflicts that need to be resolved before we can merge. Is this PR still live?

**Comment by MuruganChandrasekar** [comment]
> 
> 
> @MuruganChandrasekar where are we on this? there are conflicts that need to be resolved before we can merge. Is this PR still live?

Yes, this PR is still live. I want you to have look at changes and test it on your end before doing merge.

**Comment by MuruganChandrasekar** [comment]
Yes. but our motive is to run the selected task given to crontab while building.

**Pull request merged**
